name: Build Kubernetes Artifact

on:
  workflow_call:
    inputs:
      image:
        required: true
        type: string

runs:
  using: "composite"
  steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Update values.yaml
      uses: fjogeleit/yaml-update-action@main
      with:
        valueFile: '../../pipeline-test/app.yaml'
        propertyPath: 'spec.template.spec.containers[0].image'
        value: ${{ inputs.image }}
        branch: main/${{ inputs.image }}
        targetBranch: main
        createPR: true
        message: 'Update Image Version to ${{ inputs.image }}'
